meta_product_name: "Myra"
meta_title: "Myra - All your subscriptions in one place"
meta_description: "Myra is the webapp that will allow you to easily manage all your subscriptions from one place"
meta_image: "MiraLogo.png"